# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines

pool: Default

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'python3.10 -m zipapp src -m "bacnet_client.app:main"'
    workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'build_exec'

